name: LookubPlugin
version: 0.0.1
author: TyoIV
main: mainPackage.mainClass
commands:
  alert:
    description: alert send at all players
    permission: lookub.alerte.use
  money:
    description: money command
    permission: lookub.money.use
  upgrade:
    description: Command when you can upgrade your grade
    permission: lookub.upgrade.grade.use
  creeper:
    description: You can spawn a creeper near you
    permission: lookub.spawn.creeper.use